### ISSUE TITLE
I cannot connect to my Odoo Database hosted on a remote server. 

### ISSUE THREAD

**Issue by kasback** [tbondois/odoo-ripcord#2]
Hello and thank you for this plugin , 
Im trying to connect to a an Odoo 12.0 Database through XML-RPC On a laravel App

MY CODE  : 
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Ripoo\OdooClient;

class ContactsController extends Controller
{
    public $url = '51.83.75.97:8069';
    public $db = 'Caudigef';
    public $user = 'admin';
    public $password = '***';

    public function all() {
        $client = new OdooClient($this->url, $this->db, $this->user, $this->password);
        var_dump($client);
    }

}`

THE OUTPUT OF THE VAR_DUMP : 

object(Ripoo\OdooClient)#206 (11) { ["apiUrl":"Ripoo\OdooClient":private]=> string(25) "51.83.75.97:8069/xmlrpc/2" ["uid":"Ripoo\OdooClient":private]=> NULL ["user":"Ripoo\OdooClient":private]=> string(5) "admin" ["db":"Ripoo\OdooClient":private]=> string(8) "Caudigef" ["password":"Ripoo\OdooClient":private]=> string(13) "****" ["createdAt":"Ripoo\OdooClient":private]=> float(1554220597.4608) ["pid":"Ripoo\OdooClient":private]=> string(31) "#xmlrpc/2-1554220597.4608-82227" ["currentEndpoint":"Ripoo\OdooClient":private]=> NULL ["services":"Ripoo\OdooClient":private]=> array(0) { } ["serviceFactory":"Ripoo\OdooClient":private]=> object(Ripoo\Service\ServiceFactory)#201 (0) { } ["response"]=> NULL }

**Comment by tbd-tbd** [comment]
Hello,

you are printing the object, but you didn't did any call yet.

To test the connection, try this :

$result = client->$client->version();
var_dump($result);
$result = $client->get_fields("res.partner");
var_dump($result);

At this moment you will either have an exception if the connection fails, or some results.
